title: "Mental Health Data Story"
description: "An exploratory data narrative using three datasets."

# Use Just-the-Docs with GitHub Pages
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

just_the_docs:
  color_scheme: "light"

url: "https://dj2513.github.io/mental-health-data-story"